"""Finalized execution metadata exposed by observe_execution."""

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict

from sentinelai.contracts import TerminalExecutionStatus


class ExecutionMetadata(BaseModel):
    """Correlation identifiers and finalized timing for one observed execution.

    These values are generated by the SDK and carried by execution-stream events.
    Platform subscribers persist them; customers may optionally read them when an
    API response needs the same correlation IDs.
    """

    model_config = ConfigDict(frozen=True)

    execution_id: UUID
    trace_id: str | None = None
    latency_ms: float | None = None
    execution_status: TerminalExecutionStatus
    intent: str | None = None


class ObservedResult[T](BaseModel):
    """Optional envelope that pairs a business return value with telemetry metadata."""

    model_config = ConfigDict(frozen=True, arbitrary_types_allowed=True)

    value: T
    metadata: ExecutionMetadata


__all__ = ["ExecutionMetadata", "ObservedResult"]
